version: '3'
services:
  db:
    image: mysql 
    env_file:
      - db.env
    volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        - mysql_data:/var/lib/mysql 
    networks:
     backup:
      ipv4_address: "172.0.0.2"
    healthcheck:
      test: ["CMD", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  extractor:
    image: shreyasssarve/extractor-microservice:v1.0.0
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - extractor.env
    networks:
     backup:
      ipv4_address: "172.0.0.3"
      
  api:
    image: shreyasssarve/photus
    ports:
      - "8080:8080"
    env_file:
      - backup.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/evendead/Pictures/Backup/:/data
    networks:
      backup:
        ipv4_address: "172.0.0.4"
networks:
  backup:
    ipam:
      driver: default
      config: 
        - subnet : "172.0.0.0/24"
volumes:
  mysql_data:
    external : true
